// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc.proto

It has these top-level messages:
	NoticeRequest
	NoticeReply
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message
type NoticeRequest struct {
	AppId   []byte `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	UserId  int32  `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Cmd     int32  `protobuf:"varint,3,opt,name=cmd" json:"cmd,omitempty"`
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *NoticeRequest) Reset()                    { *m = NoticeRequest{} }
func (m *NoticeRequest) String() string            { return proto.CompactTextString(m) }
func (*NoticeRequest) ProtoMessage()               {}
func (*NoticeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NoticeRequest) GetAppId() []byte {
	if m != nil {
		return m.AppId
	}
	return nil
}

func (m *NoticeRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *NoticeRequest) GetCmd() int32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *NoticeRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// The response message
type NoticeReply struct {
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
}

func (m *NoticeReply) Reset()                    { *m = NoticeReply{} }
func (m *NoticeReply) String() string            { return proto.CompactTextString(m) }
func (*NoticeReply) ProtoMessage()               {}
func (*NoticeReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NoticeReply) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*NoticeRequest)(nil), "rpc.NoticeRequest")
	proto.RegisterType((*NoticeReply)(nil), "rpc.NoticeReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
//const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	// notice
	Notice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeReply, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Notice(ctx context.Context, in *NoticeRequest, opts ...grpc.CallOption) (*NoticeReply, error) {
	out := new(NoticeReply)
	err := grpc.Invoke(ctx, "/rpc.User/Notice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserServer interface {
	// notice
	Notice(context.Context, *NoticeRequest) (*NoticeReply, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Notice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Notice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.User/Notice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Notice(ctx, req.(*NoticeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notice",
			Handler:    _User_Notice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x31, 0xef, 0x82, 0x30,
	0x10, 0xc5, 0xff, 0xfc, 0x81, 0x12, 0x4f, 0x4d, 0xc8, 0x25, 0xc6, 0xc6, 0x09, 0x99, 0x98, 0x88,
	0xd1, 0xc5, 0xaf, 0xc0, 0xe2, 0xd0, 0xc4, 0xd9, 0xd4, 0xb6, 0x03, 0x11, 0xd3, 0xb3, 0xc0, 0xc0,
	0xb7, 0x37, 0xad, 0x61, 0x60, 0x7b, 0xef, 0x97, 0xcb, 0xbd, 0xf7, 0x60, 0xe5, 0x48, 0xd5, 0xe4,
	0xec, 0x60, 0x31, 0x76, 0xa4, 0xca, 0x17, 0x6c, 0x6f, 0x76, 0x68, 0x95, 0x11, 0xe6, 0x33, 0x9a,
	0x7e, 0xc0, 0x1d, 0x30, 0x49, 0xf4, 0x68, 0x35, 0x8f, 0x8a, 0xa8, 0xda, 0x88, 0x54, 0x12, 0x35,
	0x1a, 0xf7, 0x90, 0x8d, 0xbd, 0x71, 0x9e, 0xff, 0x17, 0x51, 0x95, 0x0a, 0xe6, 0x6d, 0xa3, 0x31,
	0x87, 0x58, 0xbd, 0x35, 0x8f, 0x03, 0xf4, 0x12, 0x39, 0x64, 0x24, 0xa7, 0xce, 0x4a, 0xcd, 0x93,
	0xf0, 0x62, 0xb6, 0xe5, 0x11, 0xd6, 0x73, 0x18, 0x75, 0x13, 0x22, 0x24, 0xca, 0x6a, 0x13, 0x82,
	0x52, 0x11, 0xf4, 0xf9, 0x0a, 0xc9, 0xbd, 0x37, 0x0e, 0x4f, 0xc0, 0x7e, 0xa7, 0x88, 0xb5, 0xaf,
	0xbc, 0x28, 0x79, 0xc8, 0x17, 0x8c, 0xba, 0xa9, 0xfc, 0x7b, 0xb2, 0xb0, 0xea, 0xf2, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0xff, 0xad, 0xd7, 0xa8, 0xe2, 0x00, 0x00, 0x00,
}
