//
// Copyright (c) 2017 SongCF <songcf_faith@foxmail.com>.
// file generated by proto4go
// https://github.com/songcf/proto4go
//

package pb

var Code = map[string]int{
	"error_ntf":     10012, // 通用错误
	"login_req":     10020, // 用于登录服务器 验证
	"login_ack":     10021, // 用于登录服务器 验证 返回
	"offline_ntf":   10032, // 推送下线消息
	"join_req":      20010, // 加入场景请求
	"join_ack":      20011, // 加入场景返回
	"join_ntf":      20012, // 加入场景推送
	"user_list_ntf": 20013, // 推送其它格子的玩家列表
	"leave_req":     20020, // 离开场景请求
	"leave_ack":     20021, // 离开场景返回
	"leave_ntf":     20022, // 离开场景推送
	"move_req":      20030, // 场景移动请求
	"move_ack":      20031, // 场景移动返回
	"move_ntf":      20032, // 场景移动推送
	"broadcast_req": 20040, // 场景广播请求
	"broadcast_ack": 20041, // 场景广播返回
	"broadcast_ntf": 20042, // 场景广播推送
	"query_pos_req": 20050, // 查询位置请求
	"query_pos_ack": 20051, // 查询位置返回
	"heartbeat_req": 20061, // 系统预留，用于表示心跳
	"heartbeat_ack": 20062, // 心跳回复包
}

var RCode = map[int]string{
	10012: "error_ntf",     // 通用错误
	10020: "login_req",     // 用于登录服务器 验证
	10021: "login_ack",     // 用于登录服务器 验证 返回
	10032: "offline_ntf",   // 推送下线消息
	20010: "join_req",      // 加入场景请求
	20011: "join_ack",      // 加入场景返回
	20012: "join_ntf",      // 加入场景推送
	20013: "user_list_ntf", // 推送其它格子的玩家列表
	20020: "leave_req",     // 离开场景请求
	20021: "leave_ack",     // 离开场景返回
	20022: "leave_ntf",     // 离开场景推送
	20030: "move_req",      // 场景移动请求
	20031: "move_ack",      // 场景移动返回
	20032: "move_ntf",      // 场景移动推送
	20040: "broadcast_req", // 场景广播请求
	20041: "broadcast_ack", // 场景广播返回
	20042: "broadcast_ntf", // 场景广播推送
	20050: "query_pos_req", // 查询位置请求
	20051: "query_pos_ack", // 查询位置返回
	20061: "heartbeat_req", // 系统预留，用于表示心跳
	20062: "heartbeat_ack", // 心跳回复包
}
